### ISSUE TITLE
Bucle de redirección con Nginx

### ISSUE THREAD

**Issue by gGonz** [vinco/wordpress-workflow#14]
Cuando se levanta un WordPress-Workflow con Nginx (por default), al ingresar a algunas urls con parámetros se crea un bucle de redirección infinito.

Por ejemplo:
`http://wordpress.local/team/anne-doe/?id_p=43`

```
# nginx access.log
GET /team/anne-doe/?id_p=43 HTTP/1.1" 302 5
GET /team/anne-doe/?q=/team/anne-doe/&id_p=43 HTTP/1.1" 302 5
GET /team/anne-doe/?q=/team/anne-doe/&q=/team/anne-doe/&id_p=43 HTTP/1.1" 302 5
GET /team/anne-doe/?q=/team/anne-doe/&q=/team/anne-doe/&q=/team/anne-doe/&id_p=43 HTTP/1.1" 302 5
```

Esto es por un error de configuración en el archivo [wordpress.nginx](https://github.com/vinco/wordpress-workflow/blob/master/provision/templates/wordpress.nginx#L13-16) que se muestra de la siguiente forma:
```
location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;

    }
```

De acuerdo a la [documentación oficial de WordPress](http://codex.wordpress.org/Nginx) debería ser:
```
location / {
        try_files $uri $uri/ /index.php?$args;
    }
```

**Comment by haga87** [comment]
Integrado en pull-request #15
